name = "solarbright-energy"
compatibility_date = "2025-01-01"

compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[build]
command = "npm run build"

[env.production]
# Add your environment variables here
# e.g., NEXT_PUBLIC_SITE_URL = "https://solarbright.com"
