name = "solarbright-energy"
compatibility_date = "2024-12-01"

compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[env.production]
# Add your environment variables here
# e.g., NEXT_PUBLIC_SITE_URL = "https://solarbright.com"
